name: graphql-api
version: 0.1.0
synopsis: Sketch of GraphQL stuff
description: Please see README.md
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/graphql-api
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

executables:
  graphql-api-example:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - graphql-api

library:
  source-dirs: src
  dependencies:
    - aeson
    - graphql
    - text

tests:
  graphql-api-tests:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - aeson
      - graphql
      - graphql-api
      - tasty
      - tasty-hspec
