name: graphql-api
version: 0.1.0
synopsis: Sketch of GraphQL stuff
description: Please see README.md
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
license-file: LICENSE.Apache-2.0
github: jml/graphql-api
category: Web

# NB the "redundant constraints" warning is a GHC bug: https://ghc.haskell.org/trac/ghc/ticket/11099
ghc-options: -Wall -fno-warn-redundant-constraints
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications

dependencies:
  - base >= 4.9 && < 5
  - protolude
  - exceptions
  - transformers
  - attoparsec

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - QuickCheck
    - text

tests:
  graphql-api-tests:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - aeson
      - containers
      - graphql-api
      - hspec
      - tasty
      - tasty-hspec

  graphql-api-doctests:
    main: Doctests.hs
    ghc-options: -threaded
    source-dirs: tests
    dependencies:
      - doctest
